### ISSUE TITLE
Configure default status

### ISSUE THREAD

**Issue by rolandschaub** [luyadev/luya-module-mailchimp#10]
It should be possible to configure the default status for subscribers added through the API. In order to enable double opt-in, the status has to be set to "pending" instead of "subscribed", see:

https://stackoverflow.com/questions/31251271/realize-mailchimp-double-opt-in-with-api-3-0
and
http://developer.mailchimp.com/documentation/mailchimp/guides/manage-subscribers-with-the-mailchimp-api/

**Comment by nadar** [comment]
@rolandschaub i have added new options for double opt in module config and direct helper class. Please try and let me know if this works as expected. The old (2.0) API is absolutely bad written and documented, we should think about moving to version 3.0 of the mailchimp api!

**Comment by TheMaaarc** [comment]
Seems to be working well. 👍

**Comment by nadar** [comment]
@TheMaaarc thanks for the response, i will release it asap.
